### ISSUE TITLE
Faild to load DLL in Unity5

### ISSUE THREAD

**Issue by ghost** [sloopidoopi/Spout4Unity#3]
Failed to load 'Assets/Plugins/x64/NativeSpoutPlugin.dll' with error '找不到指定的模組。
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly.
Spout.SpoutSender:OnDisable() (at Assets/Spout/Scripts/SpoutSender.cs:92)
Spout.SpoutSender:OnDisable() (at Assets/Spout/Scripts/SpoutSender.cs:91)

Same Project in Win8.1 is ok!

**Comment by benkuper** [comment]
You say in 8.1 it's ok, what's OS are you having problem with ?
Please be more specific in your issue

**Comment by picpic1979** [comment]
I have the same bug !
unity 5.0.2b1 32bits "latest"

Work with 64 bits editor but not 32 bits
Do you support 32 bit editor support ?

Windows 7 and 8.1

Failed to load 'Assets/Plugins/x86/NativeSpoutPlugin.dll', expected 32 bit architecture (IMAGE_FILE_MACHINE_I386), but was IMAGE_FILE_MACHINE_AMD64.
Spout.Spout:initDebugConsole() (at Assets/Spout/Scripts/Spout.cs:421)
Spout.Spout:initDebugConsole() (at Assets/Spout/Scripts/Spout.cs:421)
Spout.SpoutSender:OnEnable() (at Assets/Spout/Scripts/SpoutSender.cs:70)

**Comment by sloopidoopi** [comment]
The problem is that the x86 dll is compiled for x64 platform . I will upload a new version so at least the spoutreceiver will work on x86 (32 bit). There is still  a problem with the SpoutSender we have to figure out .

**Comment by sloopidoopi** [comment]
New version that works on Win 8.1 64bit ATI card is uploaded
