### ISSUE TITLE
Spout just send black screen

### ISSUE THREAD

**Issue by picpic1979** [sloopidoopi/Spout4Unity#4]
Hi 
I just test spout with unity 5.0.2f1 64 bits i try to run the simplesender scene, every things seem to be good unity send the texture but when i run spout2 demo receiver, i just receive unitysender with a black texture i can't see the spoutcam. But i have no error debug !

I really don't know why !
My config is 

unity 5.0.2f1 64 bits
gtx 980 nvidia

Thanks

**Comment by sloopidoopi** [comment]
Please check the latest release
